

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainBackgroundPanel;
                ref class TextBlock;
                ref class TextBox;
                ref class CheckBox;
            }
        }
    }
}

namespace GraphGenome
{
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainBackgroundPanel^ SwapChainPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txt_genome2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txt_nbiterations;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txt_lg;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txt_rdnMax;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txt_Genome;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ chk_rendergenome;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ chkRandomMode;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtRulesFileName;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txt_angleRef;
    };
}

